#!/bin/sh
# Commit message guard. Usage: commit-message.sh <message-file>
# Fails on: commit hashes in the message, a subject that is not `type(scope): subject`.
# Warns (never fails) when the staged diff spans unrelated top-level areas.
# Run with no argument (as the checks runner does) it checks nothing and exits 0.
msg="$1"
[ -n "$msg" ] && [ -f "$msg" ] || exit 0

body=$(grep -v '^#' "$msg")
subject=$(printf '%s\n' "$body" | sed -n '/./{p;q;}')
fail=0

# Merge/revert/fixup/squash subjects generated by git are exempt from the style rule.
case "$subject" in
  "Merge "*|"Revert \""*|fixup!*|squash!*|amend!*) exempt=1 ;;
  *) exempt=0 ;;
esac

if [ "$exempt" = 0 ]; then
  if ! printf '%s\n' "$subject" | grep -Eq '^(feat|fix|docs|test|chore|refactor|perf|style|build|ci|revert)(\([A-Za-z0-9._/-]+\))?!?: [^ ].*'; then
    echo "commit-message: subject must look like 'type(scope): subject' (types: feat fix docs test chore refactor perf style build ci revert)" >&2
    fail=1
  fi
fi

# A hash is a 7-40 char hex word with at least one digit and one a-f letter.
hashes=$(printf '%s\n' "$body" | grep -Eo '\b[0-9a-f]{7,40}\b' | grep '[0-9]' | grep '[a-f]' | sort -u)
if [ -n "$hashes" ]; then
  echo "commit-message: commit hashes do not belong in messages (describe the outcome instead): $(echo $hashes)" >&2
  fail=1
fi

# Bundling heuristic: three or more top-level areas outside tests and _docs.
areas=$(git diff --cached --name-only 2>/dev/null | awk -F/ '{ if (NF == 1) print "."; else print $1 }' | grep -v -x -e tests -e _docs | sort -u | wc -l)
if [ "${areas:-0}" -ge 3 ]; then
  echo "commit-message: warning: staged changes span $areas unrelated top-level areas; commits should be one logical unit" >&2
fi

if [ "$fail" = 1 ]; then
  . "$(dirname "$0")/lib/principal-override.sh"
  principal_override commit-message "$body" && exit 0
fi
exit "$fail"
