#!/bin/sh
# Commit message guard. Usage: commit-message.sh <message-file>
# Fails on: a subject that is not `type(scope): subject`.
# Commit hashes are allowed: exact source pins in commits, issue comments and receipts are
# essential. The hash ban applies only to reader-facing published pages (publication.sh).
# Run with no argument (as the checks runner does) it checks nothing and exits 0.
msg="$1"
[ -n "$msg" ] && [ -f "$msg" ] || exit 0

body=$(grep -v '^#' "$msg")
subject=$(printf '%s\n' "$body" | sed -n '/./{p;q;}')
fail=0

# Merge/revert/fixup/squash subjects generated by git are exempt from the style rule.
case "$subject" in
  "Merge "*|"Revert \""*|fixup!*|squash!*|amend!*) exempt=1 ;;
  *) exempt=0 ;;
esac

if [ "$exempt" = 0 ]; then
  if ! printf '%s\n' "$subject" | grep -Eq '^(feat|fix|docs|test|chore|refactor|perf|style|build|ci|revert)(\([A-Za-z0-9._/-]+\))?!?: [^ ].*'; then
    echo "commit-message: subject must look like 'type(scope): subject' (types: feat fix docs test chore refactor perf style build ci revert)" >&2
    fail=1
  fi
fi

if [ "$fail" = 1 ]; then
  . "$(dirname "$0")/lib/principal-override.sh"
  principal_override commit-message "$body" && exit 0
fi
exit "$fail"
